### ISSUE TITLE
0.9.16 docker image is missing

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#1707]
**Describe the bug**

![image](https://user-images.githubusercontent.com/4329072/104794907-c342e300-57e5-11eb-8d5e-83b9e91cce6a.png)
https://hub.docker.com/repository/docker/jinaai/jina

0.9.15 is published on docker hub. 

**Describe how you solve it**

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
Here are the bug analyze steps:
1. We use github action to build image, so the problem is in Github action `tag.yml`
2. Go to Github action log, find that all images building failed, because of `gcc` not found when building `lz4`
3. Given that 0.9.5 and 0.9.6 releases are just 1 hour in-between and no changes on `tag.yml`, it must be something else.
4. Ask oneself: why 0.9.5 does not need gcc where 0.9.6 suddenly needs gcc? why did it only happen for `lz4`?
5. Experience told us: though rare, it is not the first time that we had symptom for (4), something is suddenly broken at certain time.
6. Go check lz4 release history, ha! they publish a new version on Jan.16 the time we build the image.
![image](https://user-images.githubusercontent.com/2041322/104807567-2d588980-57e0-11eb-9dbe-f3468f9cc114.png)

So that's it! By the time they publish it, wheels were not ready (what is a wheel? plz google). Therefore we have to build by ourselves from scratch using gcc, as all `latest` versions do not include `build-essential` for the sake of image size, the building failed.

Solution? Bad timing, just wait. Go check https://pypi.org/simple/lz4/ and realize all wheels are ready now 
![image](https://user-images.githubusercontent.com/2041322/104807596-65f86300-57e0-11eb-80b9-75c4a4673c44.png)

Todo @jina-ai/engineering 

- add a new action that publishes image manually after something fails again like this. Where to learn, how about start from copy-paste related section in `tag.yml`?
- Learn what is wheel?
- Learn how to analyze the bug like this.
