### ISSUE TITLE
codecov can't show files details

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#1769]
Codecov cannot show details of the lines covered due to some path fixing issue.

See https://docs.codecov.io/docs/fixing-paths for more info.

**Comment by delgermurun** [comment]
Hello @JoanFM,

I'd like to work on it. Could you elaborate it more, please?
I couldn't understand what is the problem here. 

I can see which lines covered or not from [codecov.io report](https://codecov.io/gh/jina-ai/jina/src/master/jina/clients/base.py).
![image](https://user-images.githubusercontent.com/492616/105630988-f3921d80-5e86-11eb-8fe8-df6dc3679c9d.png)

But I guess it is not "details of the lines covered". What is "details of the lines covered" exactly and how can I see it (maybe from other project reports)? Sorry, I am super new to Jina and Codecov.

Thanks!

**Comment by delgermurun** [comment]
Oh, maybe I got what is a problem here.

@JoanFM Did you mean Codecov can't show commit diff?
![image](https://user-images.githubusercontent.com/492616/105631422-5a183b00-5e89-11eb-93d3-4e228d263eee.png)

---

I can see a nice diff report on `Diff` tab (ex: [`scrapy/scrapy` commit](https://codecov.io/gh/scrapy/scrapy/commit/43062969ea243f5b5d8060a0230100f23e05056f)).

**Comment by JoanFM** [comment]
Ok, I could not access earlier, so I guess there is no longer an issue. Thank you very much anyway for your interest and collaboration
