### ISSUE TITLE
Support for full-text features like filtering

### ISSUE THREAD

**Issue by antoniolanza1996** [jina-ai/jina#1803]
**Describe the feature**
Hey folks,
this issue is closely related to #527. @hanxiao you said that you were in the progress of implementing full-text features, do you have some news on this topic?

I see that we can store some metadata in `Document.tags` variable. But is there a strategy in Jina to filter based on `tags` keys during querying? For example, I was thinking at something like: 
```python
d1 = Document(text="...")
d2 = Document(text="...")
#...

d1.tags['name'] = "Antonio"
d2.tags['name'] = "John"
#...

#step 1: encode with a TransformerTorchEncoder and index all documents

#step 2: run a vector search but only on a subset of indexed documents: those that have tags['name'] = "Antonio"
```

**Comment by JoanFM** [comment]
Hey @antoniolanza1996 ,

We have such a feature by adding QueryLanguageDrivers to your search. You can try to add a FilterQL driver after the retrieval step of your documents to retrieve only the documents matching some criteria.

**Comment by antoniolanza1996** [comment]
Hey @JoanFM ,
thanks for the quick answer.

Great to hear :) Any Jina documentation link or starting point suggestions that will help me on diving into this topic?

Furthermore, from your first comment I've understood the FilterQL works **after** vector search. Is there anything that works **before** vector search?

**Comment by nan-wang** [comment]
hi, @JoanFM You might want to check out this example. https://github.com/jina-ai/examples/tree/master/fashion-example-query

**Comment by antoniolanza1996** [comment]
Hey @nan-wang , thanks for the link. I went through on this example however I didn't find a use case similar to what I'm trying to explain. As I understand, `FilterQL` is used to filter out documents from the _**request documents**_ i.e. Jina input of index/search.
However, I'm looking for something that receive a general image (i.e. without `tags` on this request Document) and find the `top_k` only between a subset of the indexed images where the subset is defined by a value in the `tags`.

Probably in the image-to-image search is not really clear but if you consider my first example (i.e. text-to-text search) surely could be better. I wanna index 500 text documents where each one has a `tags['name']`. Let's suppose that 100 have `tags['name'] = "Antonio"` and 400 have `tags['name'] = "John"`.
After, I want to query this index with a vector search, but only on 100 documents which have `tags['name'] = "Antonio"`.

In essence I want to run something similar when using both [terms query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html) and a [script query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-script-score-query.html#query-dsl-script-score-query) on [dense vectors](https://www.elastic.co/guide/en/elasticsearch/reference/current/dense-vector.html) in Elasticsearch.

**Comment by tadej-redstone** [comment]
This is not possible with Jina. OpenDistro Elasticsearch has similar functionality for their [knn](https://opendistro.github.io/for-elasticsearch-docs/docs/knn/) query.

**Comment by tadej-redstone** [comment]
I should also add that this feature will probably not appear in Jina for quite some time. Well, it may be a part of Jina's default `NumpyIndexer`, but it won't appear in any useful 3rd party indexers such as FAISS. That's simply because these indexers do not implement any pre-filtering - they are more of an outgrowth of several research paper than serious production-ready libraries.

The OpenDistro knn is the closest you can get. It implements pre-filtering, although it then defaults to default (slow) knn, instead of using the HNSW ann algorithm, so you'll need to be careful about when to use pre-filtering. In this case I would recommend using jina only for encoding and relying on OpenDistro for indexing

**Comment by nan-wang** [comment]
> Probably in the image-to-image search is not really clear but if you consider my first example (i.e. text-to-text search) surely could be better. I wanna index 500 text documents where each one has a tags['name']. Let's suppose that 100 have tags['name'] = "Antonio" and 400 have tags['name'] = "John".
After, I want to query this index with a vector search, but only on 100 documents which have tags['name'] = "Antonio".

hi, @antoniolanza1996 As @tadej-redstone mentioned, this is untrivial for vector-based indexes and the most of the 3rd party indexers support this kind of search. Currently, there two solutions,

1. when the number of filters is limited as shown in the example, one can build separated indexes for each value. In your case, one indexer for `Antonio` and one indexer for `John`. Then one can use the `QueryLang` to select which index to query. (Anyway, I know this is really a dirty hack)

2. when the number of filters is big, assuming that you need to search among 1000 people, one can index all the data in one index. In this case, we need to retrieve more data than we want to have and afterwards use `FilterQL` to select the matched ones. Suppose that you want to get K results back, you might need to retrieve (N*K) results from the vector indexer.

**Comment by antoniolanza1996** [comment]
Hey @tadej-redstone, I have never used OpenDistro ES but it seems similar to what we can do with terms query and a script query on dense vectors in the official Elasticsearch.

>The OpenDistro knn is the closest you can get. It implements pre-filtering, although it then defaults to default (slow) knn, instead of using the HNSW ann algorithm

Yes, indeed this is the real problem: ES KNN search is really slow compared to other solutions.

@nan-wang , your 1st solution could be acceptable, but it's not trivial if you have more `tags` variable to filter - the number of indexes grows significantly.

Anyway, thanks both for your advises. 

---
Hence, in Jina roadmap there are no full-text features? As well as symbolic-based approaches like TF-IDF or BM25 with the aim of scoring all indexed texts compared to an input textual query.

**Comment by tadej-redstone** [comment]
@antoniolanza1996 OpenDistro ES supports an ANN (*Approximate* nearest neighbors) query - it uses HNSW for that, which is also supported by FAISS, for example. That's why it will be a few magnitudes faster than the KNN query. But as I said, if you want pre-filtering, a KNN query will be executed. A similar flow could probably be constructed in Jina I suppose

**Comment by JoanFM** [comment]
> Hey @tadej-redstone, I have never used OpenDistro Elasticsearch but it seems similar to what we can do with terms query and a script query on dense vectors in the official Elasticsearch.
> 
> > The OpenDistro knn is the closest you can get. It implements pre-filtering, although it then defaults to default (slow) knn, instead of using the HNSW ann algorithm
> 
> Yes, indeed this is the real problem: Elasticsearch KNN search is really slow compared to other solutions.
> 
> @nan-wang , your 1st solution could be acceptable, but it's not trivial if you have more `tags` variables to filter - the number of indexes grows significantly.
> 
> Anyway, thanks both for your advises.
> 
> Hence, in Jina roadmap there are no full-text features? As well as symbolic-based approaches like TF-IDF or BM25 with the aim of scoring all indexed texts compared to an input textual query.

Hey @antoniolanza1996 ,

Currently we cannot leverage prefiltering the documents before the NN search beyond the solution that @nan-wang gave, however we have the `QueryLang` message that can be sent along with the `Request` messages to override a `FilterQL` parameters so that u can adapt your FIltering Query for each request. (https://docs.jina.ai/chapters/proto/docs.html#querylangproto) Right now I do not find a good piece of documentation for this feature beyond this one (https://hanxiao.io/2020/08/28/What-s-New-in-Jina-v0-5/), however in the next days we are gonna give a strong bump to them (apologies for that).

So in this sense, we can provide the same interface but the NN search will be done on the full collection, thus you may need to count for a larger top_k to guarantee you have enough results in output.
