### ISSUE TITLE
Inconsistent links that refer to jina docs 101

### ISSUE THREAD

**Issue by Immich** [jina-ai/jina#1960]
Throughout the docs, there are many references to Jina docs(101). Some links go to https://docs.jina.ai/chapters/101/index.html and some to the repo where all the docs used to be (https://github.com/jina-ai/docs/tree/master/chapters/101).

I could help with that, I would just need to know where will the links need to point.

**Comment by bwanglzu** [comment]
@Immich Hi thanks! could you give an example of the issue you mentioned above? I mean give an example of `inconsistency` as you mentioned above.

**Comment by alexcg1** [comment]
Oh dang, I just saw this. I wrote a quick script to do this in most cases: https://gist.github.com/alexcg1/c689ae35e103422e965b682ae74bd0b9

I've submitted PRs to core and docs repos. @Immich I don't think I've done examples repo yet though - that's bound to have some links to change.

Another gist to output all filenames that contain the string `101` (excluding certain filetypes): https://gist.github.com/alexcg1/c6f14c59040c71329e97feba5b12a5b5

**Comment by alexcg1** [comment]
The above scripts need the tools `sd` (better `sed`) and `ripgrep` (better `grep`)

**Comment by alexcg1** [comment]
I don't suggest just doing this automatically btw - there are some edge cases involved.

If you can find a simple tool to ask each time if you want to replace, that would be best

Manual way I did it:

1. Go to repo directory
2. Run the `rg` gist above and pipe into vim (excluding the `--color always` bit)
3. Hit `J` a bunch of times in vim to put all one line and copy to system clipboard
4. Quit vim
5. Then run `vim <clipboard output>` to open ALL the files in vim
6. Copy `https://101.jina.ai` to a separate clipboard register: `"ay` (yank to register `a`)
7. `/101` to find lines with 101
8. Since bad link usually in brackets, go to the link and `dib` (delete in brackets)
9. Hit `"ap` (paste from register `a`)
10. `n` to get next hit
11. `:Gw` to save and add to git
12. `:bd` to close that file
13. Rinse and repeat

**Comment by FionnD** [comment]
Can this issue be closed? If the issue was only related to 101, it should be fixed now @alexcg1 right?

**Comment by Immich** [comment]
I made a PR which was merged today in the examples repo. I believe everything is ok now 😄

**Comment by alexcg1** [comment]
Nice @Immich !
