### ISSUE TITLE
CRUD demo binder dose not run correctly

### ISSUE THREAD

**Issue by FionnD** [jina-ai/jina#2022]
**Describe the bug**
When trying to run the binder for CRUD, a number of python errors are thrown. 
Starting with the emoji as custom indexes, and error in the RuntimeFailToStart for following sections. 

**Environment**
https://hub.gke2.mybinder.org/user/jina-ai-jupyter-notebooks-cjw9jyn6/notebooks/basic-basic-crud-functions.ipynb

**Steps to fix**
1. Begin by debugging the reason why emoji are not accepted as custom indexes. 
2. Check that all other fields in the notebook will run after your fix. If there is other issues, fix them. 
2. Once you found a fix to this, open a PR in the jina-ai jupyter notebook repo.

**Comment by willperkins** [comment]
It looks like [mybinder.org](http://mybinder.org) was using an older version of Jina (0.9.27) that didn’t yet provide support for dragon head doc id’s.

![image](https://user-images.githubusercontent.com/576702/109022017-b5715f00-76bb-11eb-8bb7-2cf75c4abffa.png)

From the binder launch log:

![image](https://user-images.githubusercontent.com/576702/109022041-bbffd680-76bb-11eb-8abb-492aa3905dc9.png)

Since the [requirements.txt](https://github.com/jina-ai/jupyter-notebooks/blob/fdb2b80fef1c6a9c01697197912b391b3680a639/requirements.txt#L1) file of the jupyter-notebooks repo doesn’t provide a version number for jina, this may lead to an unexpected jina version being loaded.

It looks like in the [binder examples](https://github.com/binder-examples/requirements), for pip requirements they pin the requirements. Maybe it would be a good idea to provide the jina version number in the [requirements file](https://github.com/jina-ai/jupyter-notebooks/blob/fdb2b80fef1c6a9c01697197912b391b3680a639/requirements.txt#L1https://github.com/jina-ai/jupyter-notebooks/blob/fdb2b80fef1c6a9c01697197912b391b3680a639/requirements.txt#L1) to avoid this caching issue.

**Comment by FionnD** [comment]
Yeah that sounds like a good fix just adding ` >=,` would you be willing to do that @willperkins?

**Comment by willperkins** [comment]
@FionnD sure thing! I opened a PR here: [#7](https://github.com/jina-ai/jupyter-notebooks/pull/7)

**Comment by FionnD** [comment]
Thanks @willperkins , really appreciate your contribution! 🥳  

I added some of the team as reviewers.
