### ISSUE TITLE
All CRUD operations should meet industry standards for idempotency

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2070]
# Research Ticket 

Users of Jina expect to see what they are familiar with when working with other frameworks. 

<p></p>

This ticket should not take more than two days of research!!

<p></p>

**Task**: To research best practices for idempotency in endpoints and apply these to all CRUD endpoints [Rest & gPRC]. For example, if a user triggers an insert three times by accident. What should happen? 

<p></p>

**References**: <https://medium.com/google-cloud/building-apis-with-grpc-continued-f53b5a5ab850>

<p></p>

**Acceptance criteria**:

- This ticket is done when: You have researched what endpoints standardly do in terms of idempotency. 

- This ticket is done when: You have written a proposal for what we should change to align with best practices.

<p></p>

<p></p>

<p></p>

<p></p>

<p></p>

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/7087564

**Comment by florian-hoenicke** [comment]
Index currently has the behavior mentioned in the google cloud blog post.
`CREATE methods are non-idempotent by nature; you should check for duplicate resources wherever possible.`

Update works also as proposed in the article:
`all of [the requests] will succeed but the resource stays the same, provided that there are no concurrency problems.`

**⚠️ Delete needs to be changed at Jina.**
`all the calls will fail as the resource has been removed at the first attempt.`
At the moment, the deletion of non-existent documents is silently ignored.
In combination with sharding, this will be challenging for us.

For now, we also don't have to care about concurrency because the requests are processed one after another.

**Comment by deepankarm** [comment]
> For now, we also don't have to care about concurrency because the requests are processed one after another.

Requests are asynchronous by default - [see test](https://github.com/jina-ai/jina/blob/master/tests/integration/gateway_non_blocking/test_gateway_non_blocking.py#L14)

**Comment by JoanFM** [comment]
> > For now, we also don't have to care about concurrency because the requests are processed one after another.
> 
> Requests are asynchronous by default - [see test](https://github.com/jina-ai/jina/blob/master/tests/integration/gateway_non_blocking/test_gateway_non_blocking.py#L14)

but at executor level, Requests are handled one after the other

**Comment by florian-hoenicke** [comment]
I created a related ticket to make the actual implementation:
https://github.com/jina-ai/jina/issues/2165

**Comment by florian-hoenicke** [comment]
@FionnD Is there anything left to do for this research ticket?
