### ISSUE TITLE
flow.delete - raise exception if document does not exist

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#2165]
`flow.delete` is currently idempotent.
As recommended in the following article about `grpc`, delete should not be idempotent.
https://medium.com/google-cloud/building-apis-with-grpc-continued-f53b5a5ab850
In case a resource does not exist "all the calls will fail as the resource has been removed at the first attempt."

**Comment by JoanFM** [comment]
How would this work with Requests with more than one Document? At which granularity does this apply?

**Comment by FionnD** [comment]
@florian-hoenicke do you think this will be covered in https://github.com/jina-ai/jina/issues/2220 ? 

From my understanding, it won't matter _how_ a request fails, we will just log it to the user. 

In my head, I imagine passing a batch of delete requests and seeing this log. 

`
Time.          Doc.                  Message. 
11:12:00 -- Document 1 -- Deleted successfully 
11:12:00 -- Document 2 -- Deleted successfully 
11:12:00 -- Document 3-- Not deleted! Jina could not find this document #(Because it had been deleted in the passed)
`

**Comment by florian-hoenicke** [comment]
@FionnD yes one part of it is covered in this ticket. In addition, we have to make sure that we respond with the correct status code in case of REST requests.

**Comment by FionnD** [comment]
Which is what you commented in the other issue? I'm just trying to decide if we can close this issue and handle it all in the other ticket

**Comment by florian-hoenicke** [comment]
Yes, it is about what I sad in https://github.com/jina-ai/jina/issues/2220#issuecomment-805941670
>I think we should also make sure that the error is traversed back to the client. The most common use case will be the REST interface used by the console or some flow manager. If we just log the errors, the user won't see them.
It can be a follow-up implementation.

**Comment by FionnD** [comment]
Cool, sorry for the trouble. I will close this issue because it will be part of #2220
