### ISSUE TITLE
`DocumentArray` of ` GraphDocument` elements gets a `Document` when iterating

### ISSUE THREAD

**Issue by davidbp** [jina-ai/jina#2603]
**Describe the bug**

When iterating over DocumentArray that is created with `GraphDocument` objects we get Documents.

MWE: The following code 

```
from jina.types.document.graph import GraphDocument
from jina import  Document 

d = GraphDocument()
docarray_graph = DocumentArray([d,d])

print(type(d))
print(type(docarray_graph))
print(type(docarray_graph[0]))
print('isinstance(docarray_graph[0], GraphDocument)=',isinstance(docarray_graph[0], GraphDocument))
print('isinstance(d,GraphDocument)=', isinstance(d,GraphDocument))
```

prints

```
<class 'jina.types.document.graph.GraphDocument'>
<class 'jina.types.arrays.document.DocumentArray'>
<class 'jina.types.document.Document'>
isinstance(docarray_graph[0], GraphDocument)= False
isinstance(d,GraphDocument)= True
```

But it should print

```
<class 'jina.types.document.graph.GraphDocument'>
isinstance(docarray_graph[0], GraphDocument)= True
```

**Comment by JoanFM** [comment]
There is a problem here:

#2604 tries to fix this (However, the performance cost of iterating over `DocumentArray` may be too large for such an important `feature` in all the `Executors`.

Why does this behavior happen?

`DocumentArray` stores a `_docs_proto` object that stores a list of `Doc_views` (Documents or DOcumentProtos) and pretends to be good at living with all of them.

And therefore, since it does not know when iterating if the object in `_docs_proto` is a `Document` or a `DocumentProto` it generates `Document` from this input which is itself a valid `Document` input
