### ISSUE TITLE
Need to enable `spawn` as potential `process starting` method.

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#2691]
**Describe the feature**
As described in #2514 , we need to enable using `spawn` to start new Processes.

bwanglzu can u please put more context on ur findings related to `torch` and `paddle`?

Also it may involve support for `Windows`

**Comment by JoanFM** [comment]
Linked to #2514

**Comment by Yongxuanzhang** [comment]
this solution is similar when we're trying to solve this one. Could it be possible that the CUDA has been initialized during import?
https://github.com/jina-ai/jina/issues/2526

**Comment by bwanglzu** [comment]
The CUDA runtime does not support the fork start method; either the spawn or forkserver start method are required to use CUDA in subprocesses. 

This makes user unable to use GPU for 3rd deep learning libraries, such as Pytorch and PaddlePaddle, since the default multiprocessing starting method is [fork](https://github.com/jina-ai/jina/blob/5db3fb6b3c21e81c9ad63a8d49eb66e571eec069/jina/__init__.py#L26).

Please check [Pytorch Documentation](https://pytorch.org/docs/stable/notes/multiprocessing.html#cuda-in-multiprocessing)

**Comment by CatStark** [comment]
Closing but we have no way to test it.
