### ISSUE TITLE
[Docker Hub] Broken Documentation Links

### ISSUE THREAD

**Issue by Rubix982** [jina-ai/jina#3107]
**Describe the bug**
The links mentioned under "Read Tutorials" on the Docker Hub page for ['jinaai/jina'](https://hub.docker.com/r/jinaai/jina) are broken and lead to a 403, as seen in the 1st screenshot.

All the links in the 2nd screenshot are broken EXCEPT `📓 Developer Reference` which leads to https://docs.jina.ai/.

I believe this issue can be tagged as `documentation`, as well as a `good first issue`.

**Describe how you solve it**
Fixing the links. :smile: 

Unfortunately, I do not think the Docker Hub content is generated from another source, and as far my experience has been with Docker Hub, it has no option that allows users to make PRs directly on a container's page.

**Environment**
Not applicable

**Screenshots**

![image](https://user-images.githubusercontent.com/41635766/128258524-29b8e175-0af4-40f3-bfd8-596a871ae067.png)

![image](https://user-images.githubusercontent.com/41635766/128258647-7d9d70c9-da69-4232-b120-8bf46640e4c3.png)

**Comment by CatStark** [comment]
Hi @Rubix982 thanks for letting us know! we'll fix this

**Comment by vj-codes** [comment]
@CatStark are you working on this? Or else I would like to work on it!

**Comment by CatStark** [comment]
Go ahdead @vj-codes !

**Comment by Rubix982** [comment]
How will you tackle this, @vj-codes? You would need access to modify jina on Docker Hub, right?

**Comment by vj-codes** [comment]
oh yeah
@CatStark this can be done by the maintainers only then ig

**Comment by afizs** [comment]
@Rubix982 You are correct. We need access to modify the links on Docker Hub.

**Comment by Aju100** [comment]
Hey, @Rubix982  I found the minor issue regarding the markdown for href section on the last endpoint. 

![href issue](https://user-images.githubusercontent.com/29862610/131932971-e92aa438-8c60-4962-9e69-19e5737aba09.png)

Here ahref has not been marked properly since syntax has been highlighted.


Also, there is a broken CONTRIBUTING guideline please have a look through this link. 
- https://hub.docker.com/r/jinaai/CONTRIBUTING.md

Steps to reproduce:
- Go to https://hub.docker.com/r/jinaai/jina
- Select a contributing guideline
![contri](https://user-images.githubusercontent.com/29862610/131933531-0a012544-6b79-435c-9ab0-14bc573ec9a2.png)
- Get the response as 404
- It goes the same with RELEASE one too
![404](https://user-images.githubusercontent.com/29862610/131933771-5f1017fe-bec6-4a8b-9149-9a2699c63715.png)

It should redirect to page of contributing guideline instead of response of 404.

**Comment by Rubix982** [comment]
Thanks, @Aju100! As above, I'm waiting for the Jina team to work on this, as I do not have access to modify the DockerHub page.

**Comment by Aju100** [comment]
Hey @Rubix982 , let's wait the response so we can resolve this issue.

**Comment by Gadgetbo** [comment]
Ok let’s do this

**Comment by Gadgetbo** [comment]
What is a dockerhub
