### ISSUE TITLE
Readme example that works in Jupyter too

### ISSUE THREAD

**Issue by CatStark** [jina-ai/jina#3140]
This doesn't work at the moment. https://jina-ai.slack.com/archives/C0169V26ATY/p1628518726071200?thread_ts=1628510094.070200&cid=C0169V26ATY

**Comment by cristianmtr** [comment]
This is actually quite hard to achieve, since this `__file__` is not at all accessible in Jupyter Notebooks.

on Colab you need to either:
1. uplaod the notebook itself as a file
2. authenticate with GDrive to get the path to the location of the notebook in GDrive of the user https://stackoverflow.com/a/49925814

And in local Jupyter notebook, you need to do

```import os
os.path.join(_dh[0], 'Untitled.ipynb')```

this will make the code much larger. I don't think we'd like that for README, but we can put a warning that it won't work in Colab or Jupyter maybe
