### ISSUE TITLE
JinaD not mount docker.sock correctly in some mac OS

### ISSUE THREAD

**Issue by Yongxuanzhang** [jina-ai/jina#3233]
https://www.notion.so/Yongxuanzhang-3433c11f98e64460ab339b098396c427

**Comment by gaocegege** [comment]
I have a deep dive into the implementation of daemon dockerize logic, seems that https://github.com/jina-ai/jina/commit/6bea7f24258f19a9bc3aa1948ac5d9c8710765fd does not work as expected

When the jinad is running inside a Linux container on MacOS host, the `dockersock` returns `//var/run/docker.sock`. The expected value is `/var/run/docker.sock`

The PR https://github.com/jina-ai/jina/pull/2971 only works when the jinad is running on native MacOS, not in a Linux container with dind.

Ref https://github.com/jina-ai/jina/pull/2971

/cc @deepankarm

**Comment by gaocegege** [comment]
BTW, the logic of dockerize is a little tricky, it may be hard to fix this problem.

**Comment by deepankarm** [comment]
@gaocegege thanks for looking into this issue. JinaD doesn't support dind and we rely on mounting `/var/run/docker.sock` so that containers created by JinaD container can talk to the dockersock on host OS.

With #2971, I was trying to solve an issue with a particular MacOS version, which didn't seem to generalize to all `MacOS` + `docker versions`. Also we heavily rely on docker networking (which varies according to OS) to properly setup communication b/w different containers. In a later PR, I'll try to add an argument to JinaD where user can pass the host OS name.

**Comment by deepankarm** [comment]
Same as https://github.com/jina-ai/jina/issues/3998
