### ISSUE TITLE
yaml `ConstructorError` while using multiprocessing spawn start method

### ISSUE THREAD

**Issue by deepankarm** [jina-ai/jina#3323]
```python
# executor.py
from jina import Executor, requests

class Custom(Executor):
    @requests
    def foo(*args, **kwargs):
        print('foo111')


# app.py
import os
os.environ['JINA_LOG_LEVEL'] = 'DEBUG'


def main1():
    from jina import Flow
    from executor import Custom

    with Flow().add(uses=Custom) as f:
        pass


def main2():
    from jina import Flow
    from executor import Custom

    with Flow().add(uses=Custom,
                    py_modules=os.path.join(os.path.dirname(__file__), 'executor.py')) as f:
        pass

if __name__ == '__main__':
    main2() # works
    main1() # fails with the following error
    """
    yaml.constructor.ConstructorError: could not determine a constructor for the tag '!Custom'
      in "<unicode string>", line 1, column 1:
        !Custom
    """
```

Run  `JINA_MP_START_METHOD=spawn python app.py`

**Comment by tadejsv** [comment]
I tried, but unfortunately I was unable to fix. The problem is the following:

The global state of the yaml module, which has the representer for `MyExecutor`, does not get preserved when using the spawn method.

What I thought would work:
- pass global state of `yaml` module to `Process.run`. Does not work, module not pickeable. This approach also feels not very elegant

What could work:
- pass `MyExecutor` to `Process.run` - trigers re-import, and thus representer properly registered.

Problem with this idea:
- Currently `Flow.add(uses=MyExecutor)` works by transforming all arguments to CLI options (`--uses=MyExecutor`), so only strings get passed to `Process.run`. If we are willing to modify that, then this problem is solvable. Otherwise I think not
