### ISSUE TITLE
Install problem when using docker cmd

### ISSUE THREAD

**Issue by stellaHSR** [jina-ai/jina#378]
**Describe your problem**

### When I use the cmd "docker run -v "$(pwd)/j:/j" jinaai/jina hello-world --workdir /j && xdg-open j/hello-world.html", there is an error:

- Couldn't find a suitable web browser!
- Set the BROWSER environment variable to your desired browser.
- Warning: program returned non-zero exit code #1
- /usr/bin/xdg-open: 851: /usr/bin/xdg-open: www-browser: not found
- /usr/bin/xdg-open: 851: /usr/bin/xdg-open: links2: not found
- /usr/bin/xdg-open: 851: /usr/bin/xdg-open: elinks: not found
- /usr/bin/xdg-open: 851: /usr/bin/xdg-open: links: not found
- /usr/bin/xdg-open: 851: /usr/bin/xdg-open: lynx: not found
- /usr/bin/xdg-open: 851: /usr/bin/xdg-open: w3m: not found
- xdg-open: no method available for opening 'j/hello-world.html'

 
**What is your guess?**

It seems that I have to install an extra web browser or do some config? I am not sure. Any suggestion? Thanks
---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
if you are running Mac, then you use `open` instead of `xdg-open`

if you are running Linux, most of the Linux distributions have `xdg-open` pre-installed. If not, please consult `yum`, `apt` for installing `xdg-open`

Or simply open `./j/hello-world.html` manually in your browser, via file browser UI/chrome. It's just the last step.
