### ISSUE TITLE
check if method add from RepeatedContainer can save copies

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#3965]
When dealing with DocumentArray, very often the pb_body is a RepeatedContainer and not a list of DocProtos. This makes the append do a copy each time.

This is felt when matches or chunks are added. 

We should check if using add can be more efficient and analyze the pros and the cons.

**Comment by alaeddine-13** [comment]
it turns out `RepeatedContainer.add` will create an empty element at the end of the proto container and return it to be filled. This means, we will have to copy the appended document to that new empty element.

I compared 2 versions of appending, the first one uses add and then merges a document to the newly added element. The second one is the current implementation which is faster.

```
timeit.timeit("proto = container.add(); proto.MergeFrom(d._pb_body)", setup="from jina import Document; ca = Document().chunks; container = ca._pb_body; d = Document();")
Out[10]: 1.6965240160002395
timeit.timeit("proto = container.append(d._pb_body);", setup="from jina import Document; ca = Document().chunks; container = ca._pb_body; d = Document();")
Out[11]: 1.3747038350002185
```
