### ISSUE TITLE
How to deploy flow?

### ISSUE THREAD

**Issue by thepowerfuldeez** [jina-ai/jina#4149]
First of all, thank you for such a nice framework for building scalable neural search engines. 
I tried to serve executors into separate docker containers and built them using `docker build` from Dockerfile created via `jina hub new` command/. Then I successfully ran Flow-as-a-Service in my python script using smth like this
```
f = Flow().add(uses="docker://container1").add(uses="docker://container2")
with f:
    f.block()
```

My question is: how can I deploy this flow to be running on production-ready environment? We can deploy FastAPI app, but here I use docker:// directive, so if I use docker for Jina inside, it will not work.

**Comment by JoanFM** [comment]
Hey @thepowerfuldeez ,

Thanks for the interest in Jina. You can use Jina on Kubernetes as stated in https://docs.jina.ai/advanced/experimental/kubernetes/#jina-on-kubernetes

However, the way this is handled will soon change. Stay tuned because in the near future, Jina will be always to dump `configuration` files so that you can easily use and scale your Executors in the cloud using `Kubernetes` and your familiar `kubernetes tools`, and also we would provide configurations to easy deploy your Flow with `docker compose`

**Comment by thepowerfuldeez** [comment]
thank you for fast answer! I looked up for docs with Kubernetes, but it seems to me, that it still deploying with plain python script, so you need to have it running somewhere.

As a workaround now, I removed docker python api dependencies and using one docker container with all requirements for all executors at once, initiating executors from config files. This way I have only one docker container which I can use whenever I want. But correct me if I wrong, I lose replicas and sharding capabilities of Jina framework.

**Comment by JoanFM** [comment]
That is correct, with ur current structure, u can use `replication` and `sharding` but inside a docker (so as processes inside the docker) but without the desired isolation.

**Comment by JoanFM** [comment]
> thank you for fast answer! I looked up for docs with Kubernetes, but it seems to me, that it still deploying with plain python script, so you need to have it running somewhere.
> 
> As a workaround now, I removed docker python api dependencies and using one docker container with all requirements for all executors at once, initiating executors from config files. This way I have only one docker container which I can use whenever I want. But correct me if I wrong, I lose replicas and sharding capabilities of Jina framework.

As for the `k8s` thing, u are right and that's why we want to change the approach.

However,  u can still do like this:


```python
f = Flow(infratructure='K8s').add()...
f.start()
```

And like this u can start and u can drop the object and the python script.

Notice that this will not be supported very soon, but may be a good way to deploy for now on Kubernetes

**Comment by JoanFM** [comment]
Hello @thepowerfuldeez ,

Please take a look at the new documentation (https://docs.jina.ai/how-to/kubernetes/) on how to deploy Jina Flow on Kubernetes.

Since yesterday, Jina 3.0 is releases with better integration.

Hope it helps
