### ISSUE TITLE
self.workspace and self.metas.workspace

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/jina#4411]
**Describe the bug**

In this repo https://github.com/jina-ai/tmp-testing-simpleindex if you don't pass uses_metas:workspace as some value, self.workspace is None, but `self.metas.workspace` is `''` 

**Describe how you solve it**

they should both hold the same value
they should both default to something, not just `None`

**Comment by JohannesMessner** [comment]
I looked into this a bit, and to me it looks like this:
`self.metas.workspace` seems useless and confusing, since there is `self.workspace`, and you can just pass a workspace like this: `f.add(..., worskpace='work/space/')`. In that case `self.workspace` would be set, but `self.metas.workspace` would not be set.
Regarding the default, if `self.workspace` is not given, it defaults to the Flow's workspace. This in turn does not have a default.

So I propose:
1. Remove `metas.workspace` from the documentation, deprecate it, and tell people to just pass `workspace`. Maybe also remove it from the code, @JoanFM do you think that is safe? Do we ever need `metas.workspace` instead of just `workspace`? If so we can automatically set it, and still tell people not to set it manually.
2. Set a default for `flow.workspace`, based on `flow.name`.

**Comment by JohannesMessner** [comment]
Is the problem that sometimes the user wants to define a workspace in an Executor yaml, and then they need `metas.workspace`?

**Comment by JoanFM** [comment]
The problem here is with `shards`. That we try to solve the `workspace` individually for each `shard`. It is quite a mess of code, and to be honest, I think is the weakest part of the abstraction when it comes to `local`-`cloud` behavior
