### ISSUE TITLE
Check how to use the `embedding_protobuf` type for compatibility between Executors

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#4432]
Check how to integrate latest docarray feature

**Comment by hanxiao** [comment]
In docarray 0.8.9 a new arg ndarray_type is added to D/DA.o_protobuf(...) which converts framework-specific-ndarray into List / numpy.ndarray . This helps to solve the compatibility problem when one Executor writes a Torch tensor and the other Executor can not read it.
I use "helps to solve" because the final solution has to be implemented in the core, e.g. .add(..., ndarray_type/comptabible='numpy') , this ndarray_type arg has to be passed to .to_protobuf(..., ndarray) .
If we don't do this, then there is a danger that Michael points out
- embeddings - how to handle Documents initialized with different embedding types (list vs np.array vs ...) -> match function does only support specific types, however this is not documented -> maybe it would be nice to have something which aligns the types if necessary, or type information should be stored by DocumentArray
Docs & docstring in this thread https://jinaai.slack.com/archives/C018F60RBL5/p1646392922048799
