### ISSUE TITLE
Hello World Examples using Jina Hub: video missing

### ISSUE THREAD

**Issue by KaizenGirl1111** [jina-ai/jina#4434]
**Describe your proposal/problem**

While attempting the intermediate BootCamp for JINA AI, I did notice the interactive video for Hello World Examples was missing. If possible, you may assign this issue to me and I'll add a video for the hello world examples.
---

**Environment**

no-code issue

**Screenshots**

<img width="942" alt="image" src="https://user-images.githubusercontent.com/73153808/156799842-4376bab8-1118-4de5-8ab5-ae637cfb5f32.png">

**Comment by alexcg1** [comment]
Hey @KaizenGirl1111, thanks for the interest! At present we're focusing on videos that explain basic concepts and examples rather than videos for each tutorial. The reason for this is that code changes fast, so maintaining videos to keep pace with the code is really tough.

We're totally up for it if you want to create videos about Jina though! @joeyouss can talk to you more on this front
