### ISSUE TITLE
Remove `Head` entity from `Deployments` without shards

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#4503]
**Describe the feature**
With the inclusion of `linkerd` as default `service mesh` we can go and remove `head` which would imply better `QPS` and no extra hops. This will be done for all Deployments without shards. For Deployments with shards, the head will be kept.

- [ ] Remove RollingUpdate/Scale feature from `Flow`/`Deployment`/`Pod`/`JinaD`
- [ ] Implement reducing after multiple needs in the Gateway
- [ ] Set all worker Pods in the Gateway (Outside K8s)
- [ ] Make the gateway send to worker Pods
- [ ] Dont create heads for Deployments with no shards
- [ ] Change plotting
- [ ] Change `Architecture Overview` in the docs

**Comment by JoanFM** [comment]
Block by #4433

**Comment by jacobowitz** [comment]
Removing the `head` Pod for Deployments without shards will remove some functionality outside a K8s deployment and shift some responsibilities to the Gateway. 

**Features to be removed:**

1. **RollingUpdate**: Has to be removed, because the `Head` is handling the dynamic addition/removal of workers. This is not implemented in the Gateway and we are not planning to do so. In theory this could be rescued, but it does not seem to be worth it really. Within K8s it will still be possible with your regular K8s tools.
2. **Scale**: Same reasoning as RollingUpdate

Gateway assumes these responsibilities:

2. Reducing for an Executor with multiple needs (unless disabled by config). This means the Gateway will touch `Documents` and depend on DocArray.

Other necessary Changes:
* The worker Pods need to be set in the Gateway on creation
* The plotting needs to be updated

**Comment by jacobowitz** [comment]
Completing this issue also means that External Deployment cant leverage multiple replicas without additional measures (Kubernetes/LoadBalancers/...)

**Comment by jacobowitz** [comment]
I created a follow up ticket to get the external Executors right. We can close this issue before, but we should wait with a release until we have the follow up issue implemented. https://github.com/jina-ai/jina/issues/4556
Also I think the Deployment as a first class citizen issue should be done before a release: https://github.com/jina-ai/jina/issues/4502
