### ISSUE TITLE
请问如果有1亿条向量，用ann图建立关系，比如hnsw算法，这些向量和索引都是放内存吗，怎么保证服务挂了，索引的拓扑关系不用重新构建呢。

### ISSUE THREAD

**Issue by zychen-real** [jina-ai/jina#457]
**Describe the feature**

**Your proposal**

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
1. please follow the issue template
2. please read examples and tutorials to understand how Jina as a framework handles index
3. no, not all in memory. https://github.com/jina-ai/jina/issues/446#issuecomment-633013807 https://github.com/jina-ai/jina/issues/356#issuecomment-632562190

closed due to the bad format and lack of focus
