### ISSUE TITLE
bug:  Flow.num_pods returns 0 without context

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#4837]
When getting the number of pods without entering the context it always returns `0`.
However, when performing a k8s deployment, we never enter the context.
```
from jina import Flow
f = Flow().add()
print(f.num_pods)
# output 0, but should be 2 (gateway + executor)
```
```
f = Flow().add()
with f:
    print(f.num_pods)
# output 2 as expected
```

**Comment by JoanFM** [comment]
This is because deployments are not built until `start` method is called.

I agree this is not the best way, I would prefer to have some more RAII-like behavior, but this interface is meaningless and not documented, so I would not care about its usage. We could make it private, but not sure even worth the effort.
