### ISSUE TITLE
Prometheus-Kube-Stack is unable to discover JINA flow serviceMonitors

### ISSUE THREAD

**Issue by PudgyPigeon** [jina-ai/jina#4951]
Hello Jina community,
Currently, our company is trying to implement Prometheus/Grafana into our EKS cluster. Our Jina deployment and flows are working perfectly, the only problem we have is that Prometheus is unable to discover the serviceMonitor for the JINA flows. We've looked through the documentation for JINA, and have set the selectorNilHelmValues(?) to false, and also have Linkerd set up for our service mesh layer. We are using the kube-prometheus-stack Helm deployment for JINA as outlined in the docs, so we were wondering what other configurations we might need to get it working. Within our jina_flow.py file, we have also set monitoring=true.
Any assistance would be greatly appreciated

Second Post: 
When I port-forward the Prometheus UI and access it through localhost, the targets tab shows the other Prometheus serviceMonitors from the Helm chart, but nothing from the JINA deployments.
I've tried deploying the Prometheus Helm chart to the same namespace and also its own namespace, but both lead to Prometheus not discovering any of the JINA serviceMonitors. Also another strange thing has happened today, and the Prometheus-Kube-Proxy service is unable to connect (Get "http://<instance-IP>:10249/metrics": dial tcp <instace-IP>:10249: connect: connection refused )
All of our previous monitoring has been through the Kubernetes Dashboard Helm chart we deployed before so Prometheus is a bit new to us. I am wondering if there is perhaps a conflict of resources between the K8S Dashboard, Linkerd, and maybe Prometheus.

(This is a reposting from the JINA slack channel to Github Issues, as per the request of the JINA team)

@samsja

**Comment by samsja** [comment]
Hey @PudgyPigeon ! Thank you for reposting here :smiley: 

First of all 
> I am wondering if there is perhaps a conflict of resources between the K8S Dashboard, Linkerd, and maybe Prometheus
There should not be any conflict with these tools. They are serving different use-case and in k8s everything is deployed in a way that it is almost impossible to have such conflict.

Secondly. As far as I can tell Jina responsibility stop at exposing the metrics and will let the users configuring their Prometheus server, but let's see how we can fix it anyway ! Prometheus ServiceMonitor debugging can really be a pain since you don't have logs when it does not discover things.

You first step is to be able to setup a working `SerivceMonitor` independently from Jina.

I would advise you to follow these steps:

* The helm deployment of Prometheus install different `SericeMonitor` which are discoverable. What you can do is to copy paste a working `ServiceMonitor`. To get one you can do  
```bash
kubectl get servicemonitor
```
and then to get the yaml file do
```bash
kubectl get servicemonitor NAME -oyaml
``` 


Once you have this yaml, edit it and don't remove the special prometheus/helm tag just change it as minimally as possible. Change only its name and the k8s Service it is suppose to monitor and apply it. At this point Prometheus will be able to discover it.  Then remove step by step the the helm tag and other things until you the service monitor can't be discover by Prometheus. By doing so you will identify which tag is require so that Prometheus can discover the ServiceMonitor. You can then just add this tag on the ServiceMonitor tag of Jina so that it can be discover as well

**Comment by PudgyPigeon** [comment]
@samsja Thank you for getting back to me about this issue. I will follow the steps you've outlined and get back to you about what ended working for us in terms of discovering the Jina serviceMonitors.

**Comment by JoanFM** [comment]
Hey @PudgyPigeon,

Did it work for you?
