### ISSUE TITLE
Initializing `workspace` in Executor 

### ISSUE THREAD

**Issue by winstonww** [jina-ai/jina#5068]
**Context**

As per https://docs.jina.ai/fundamentals/executor/executor-api/?highlight=jina_default_workspace_base#workspace, we would expect the following:

```python
from jina import Executor

class E(Executor):
    ...

e = E(workspace='workspace')
assert e.workspace == 'workspace'

```

but `e.workspace` gives `None` in the above example if `JINA_DEFAULT_WORKSPACE_BASE` is not set.  We wonder if it is possible to address the above issue? 

Perhaps modify the workspace function in`jina/serve/executors/__init__.py` to add a default value?
```diff
@@ -321,8 +325,9 @@ class BaseExecutor(JAMLCompatible, metaclass=ExecutorType):
         workspace = (
             getattr(self.runtime_args, 'workspace', None)
             or getattr(self.metas, 'workspace')
-            or os.environ.get('JINA_DEFAULT_WORKSPACE_BASE')
+            or os.environ.get('JINA_DEFAULT_WORKSPACE_BASE', ... )
         )
```
Other suggestions are also welcome. Thanks.

**Comment by JohannesMessner** [comment]
This issue has come up before, but was deemed not important at the time. See here: https://github.com/jina-ai/jina/issues/4532
As suggested there, you can use `metas.workspace` as a workaround for now, but since you are now the second person to come across this I think we should fix it.
Thanks for raising!

**Comment by winstonww** [comment]
Gotcha, thanks for letting me know.
