### ISSUE TITLE
Client module takes long time for response to a request 

### ISSUE THREAD

**Issue by hsalehgh** [jina-ai/jina#5099]
Hi,
I have a flow running in cloud and whenever I try to connect to flow via client module to search, it takes about 14 sec! could you please help me if there is any solution for it to make it faster?

```
conn = Client(host='grpc://gateway.test.svc:8080')
results = conn.search(inputs=docs, show_progress=True)     (<<This line takes 14 sec to execute!)
```
Gateway and executors k8s manifests has been created based on jina Kubernetes page.

**Comment by hsalehgh** [comment]
I am using TorchEncoderTransformers with SimpleIndexer. I am sending one line of text to the flow. 
I am not using a private Executors but I dockerized the current executors that I mentioned and use them in my deployment

**Comment by samsja** [comment]
Are you using a GPU to compute the embedding ?

**Comment by hsalehgh** [comment]
No I am using CPU, but it is just couple of words to encode and I am using replica set for encoder pod.

**Comment by hanxiao** [comment]
```python

conn = Client(host='grpc://gateway.test.svc:8080')
results = conn.search(inputs=[], show_progress=True)
```

how long does this take?

**Comment by hsalehgh** [comment]
empty input takes only 30ms.

**Comment by hsalehgh** [comment]
Any idea in this topic? is there anything that I can do to make it faster?

**Comment by samsja** [comment]
Could you try to run the Executor code locally directly on your machine ?

```python
from docarray import Document, DocumentArray, Executor

executor = Executor.from_hub(uri='jinahub://CLIPTextEncoder', install_requirements=True)
executor.encode(DocumentArray([Document(text="your text")]))
```

this will tell you how long it takes to run the Executor code natively

I think that the model behind the torch encoder takes really long to do the forward because your machine is using CPU.

We have almost no overhead on performance when using jina (this is count is millisecond) that's why I think that it can only come from the CPU forward.

You can as well try a different (and smaller) model for this encoder or maybe use the spacy encoder (SpacyTextEncoder) which is more lightweight than this one.

**Comment by hsalehgh** [comment]
I found out that the indexer part is the problem. Encoding is fast but when it starts to search matches in indexer pod, it get stuck

**Comment by samsja** [comment]
@hsalehgh which indexer are you using ?

**Comment by hsalehgh** [comment]
Simple indexer

**Comment by samsja** [comment]
If you are storing a lot of data SimpleIndexer will suffer from performance issue, as it's name suggest this indexer is for prototyping but not for real application. I would suggest you to use a indexer backed by a Vector database

**Comment by JoanFM** [comment]
Hello @hsalehgh ,

any updates on this issue?
