### ISSUE TITLE
Rename dry_run to something better 

### ISSUE THREAD

**Issue by samsja** [jina-ai/jina#5147]
# context

`dry_run` is not clear enough we should rename to smth like `is_server_ready`

PS: lets make dry_run deprecated but still working

**Comment by JohannesMessner** [comment]
We have a different mechanism for readiness, the per-executor grpc readiness check.
This is something different, instead of just checking readiness it tries to actually send data around, hence the name.

I get that on its own, `dry_run()` is not very clear, but if we call it `is_flow_ready()`, than I am not sure things will not become even more confusing, because the naming would clash with our other readiness mechanism.

**Comment by samsja** [comment]
Yes I agree that it is not about readiness so it should bot be renamed `is_server_ready`
