### ISSUE TITLE
change default config name(config.yml) when generate k8s deploy yaml

### ISSUE THREAD

**Issue by bnuzhanyu** [jina-ai/jina#5160]
**Describe your proposal/problem**

I want to build only one docker image for multiple executors, so I just make multiple yml file in my repository instead of building multiple images.

```python
image = 'docker://xxxx'

f = (
    Flow(cors=True, port=8080, protocol="http")
    .add(
        name='Encoder',
        uses=image,
        use_config_file='emb.yml',
    )
    .add(
        name='AnnIndexer',
        uses=image,
        uses_with={'dim': 1024},
        use_config_file='indexer.yml',
    )
)

f.to_kubernetes_yaml("./k8s_flow", k8s_namespace='yyy')

```
The generated yaml for executor spec.containers.arg is:
        - --uses
        - config.yml

I have to modify the yaml files in k8s_flow for each executor, which is really boring.
Is there any way to change the config file name to my own?
I tried using entrypoint but it did not work, and the entrypoint param seems useless, it did not change anything.
e.g. `add(entrypoint="jina executor --uses emb.yml", ... )`

And is there a way to modify the image pull policy to 'Always' ?

---

**Environment**

- jina 3.8.2
- docarray 0.16.2
- jcloud 0.0.35
- jina-hubble-sdk v0.0.0
- jina-proto 0.1.13
- protobuf 4.21.5
- proto-backend upb
- grpcio 1.48.1
- pyyaml 6.0
- python 3.7.13
- platform Linux
- platform-release 3.10.0-1160.71.1.el7.x86_64
- platform-version #1 SMP Tue Jun 28 15:37:28 UTC 2022
- architecture x86_64
- processor x86_64
- uid 95530249309
- session-id 14f53638-302c-11ed-8e30-00163e0bec5d
- uptime 2022-09-09T18:42:20.246472
- ci-vendor (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DEPLOYMENT_NAME (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_EARLY_STOP (unset)
* JINA_FULL_CLI (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_GRPC_RECV_BYTES (unset)
* JINA_GRPC_SEND_BYTES (unset)
* JINA_HUB_NO_IMAGE_REBUILD (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTOUT_TELEMETRY (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
**Screenshots**

![image](https://user-images.githubusercontent.com/21094531/189336201-f51d3adf-5b2c-4f9b-92cf-8340b538fc24.png)

**Comment by JoanFM** [comment]
Hello @bnuzhanyu,

Thanks for reporting this issue. Unfortunately right now there is no way from the API for you to change this other than editing yourself the output `yaml`.  The only way for you to alter the behavior (as for instance to set Always in imagePullPolicy) would be to edit the `deployment.yml` in our `resources` folder which is kind of our `template`.

Some other questions:

- Why `entrypoint` does not work: EntryPoint works when you use Jina outside in Kubernetes but using Docker, but in this case u are already in the entrypoint of the `Docker container`. The confusion comes from the aim of Jina to facilitate the interface, for instance `entrypoint` allows `Jina` to know what to launch, but once inside the Docker container, this parameter is useless because there is only Python involved. (I hope I made it clear but not sure ...)

- `uses_config_file` is something we could consider, but we need to evaluate if it will only add confusion. 

I recommend you to adapt to the way to build your docker image here:

https://docs.jina.ai/fundamentals/executor/containerize-executor/

**Comment by JoanFM** [comment]
Hey @bnuzhanyu,

After some internal discussion with the team. We decided not to expose this `parameter`. In this case you will need to update the YAML file yourself. We will add a `warning` in documentation so that one is aware when building the Docker Images.

Thanks for reporting
