### ISSUE TITLE
Jina Flow memory leaking issues

### ISSUE THREAD

**Issue by tommykoctur** [jina-ai/jina#5589]
**Describe the bug**
Hi we tried for a week to solve memory leaking issue. 
We thought that it happening due to some code inside our executors, after some some testing it appear to be jina Flow issue. 
We have created minimal example showing gradually increasing memory. 
https://github.com/tommykoctur/jina-memory-leak.git  
Can you please check if we did some mistake in executors code or is this issue of jina ?  thank you.

**Comment by JoanFM** [comment]
Hello @tommykoctur ,

can you share the mental process and experiments that lead you to understand it is a Jina Flow issue? In other conversations it seemed to be related to Spacy Executor?

**Comment by tommykoctur** [comment]
Hi, for example I took code from encoder and run it (without flow) with the same data -> memory didn't grow. 
The same with segmenter. 

Also I tried this, which is very slow approach, but memory is stable:

`def index_data(file_path="dirty-dataset.txt"):

    with Flow.load_config("flow.yaml") as f:
        input_docs = doc_generator(filepath=file_path)
        for ddd in input_docs:
            f.post(
                on="/index",
                inputs=ddd,
                request_size=1,
                show_progress=True,
            )
        print("Done")`

So I assume, that there is some issue with passing XL generator to slow executors and executors are creating big documents (because we keeping token embeddings). 

It definitely worth investigating it.

**Comment by JoanFM** [comment]
can u show your process on how u tried with Executor alone?

**Comment by JoanFM** [comment]
I believe I understood the problem:

Every `post` request returns a DocumentArray, so the client is keeping in memory the DocumentArrays to return to the client once the post has terminated. Then they are kept in memory and that's why you see the memory increasing, and is quite fast because you set encoding and tensor, which are big in DocArray.

You should be able to iterate over the input generator yourself to control this
