### ISSUE TITLE
CUDA_VISIBLE_DEVICES=RR does not work

### ISSUE THREAD

**Issue by fqzhao-win** [jina-ai/jina#5652]
**Describe the bug**

CUDA_VISIBLE_DEVICES=RR Python xxx.py,
After running the program, it will prompt torch.cuda.is_ available() == false
**Describe how you solve it**

now i can not solve this problem
---

**Environment**

**Screenshots**

![image](https://user-images.githubusercontent.com/45990111/216551280-a23dc448-15ea-4e7f-bde1-b96286b1d384.png)

**Comment by JoanFM** [comment]
How are you using your Executor? 

I do not think this is caused by Jina having any bug. It seems like something wrong with your `cuda` setting.

**Comment by JoanFM** [comment]
What happens if u simply run this python command in ur machine?

```python
import torch
torch.cuda.is_available()
```
?

**Comment by fqzhao-win** [comment]
sorry，ijust

**Comment by fqzhao-win** [comment]
if export cuda_visible_devices=rr.the result is false

**Comment by fqzhao-win** [comment]
if export CUDA_VISIBLE_DEVICES=0 OR export CUDA_VISIBLE_DEVICES=0,the result is true

**Comment by fqzhao-win** [comment]
if export CUDA_VISIBLE_DEVICES=0 OR export CUDA_VISIBLE_DEVICES=1,the result is true

**Comment by fqzhao-win** [comment]
> 

It's possible

**Comment by fqzhao-win** [comment]
> It's possible

It's possible

**Comment by JoanFM** [comment]
Ah I see your point. 

CUDA_VISIBLE_DEVICES=RR will make sure that Jina assigns a different DEVICE for every Replica, but here you are using `torch` before the `Executors` are up (They are being called in the main process) and this is why it fails.

So this is what is happening:

```
main Process -> env Var CUDA_VISIBLE_DEVICES=RR -> If torch tries to access it will not understand
Process Replica 1 -> env var CUDA_VISIBLE_DEVICES=0
Process Replica 2 -> env var CUDA_VISIBLE_DEVICES=1
```

So you need to avoid `torch.cuda` to be called in the main process.

Another option you have is to set the `CUDA_VISIBLE_DEVICES=RR` in the `env` argument of the `Executor` where there is needed in the Flow.

**Comment by JoanFM** [comment]
Hello @ruanrz, @fqzhao-win ,

I believe what happens is that torch is imported before the Executor starts and this is why the CUDA_VISIBLE_DEVICES takes place.

Would u try doing these things (one or the other)
1- Refactor ur code to separate the Executor and the Flow and include the Executor from a module or a file (https://docs.jina.ai/concepts/flow/add-executors/#define-executor-with-uses)
2- Keep it as it is, but hide the import torch inside the method where this is needed, so that the module is not imported from the start and affectes the new processes of Executors

I believe this should solve your issues.
