### ISSUE TITLE
async or sync?

### ISSUE THREAD

**Issue by wqh17101** [jina-ai/jina#5719]
![image](https://user-images.githubusercontent.com/26429138/221543134-da1078c0-382d-40c2-a88e-a2ee1717d10e.png)
I found an example in you docs.
Here are questions made me confused:
1. you can see that you add `async` before the `def` which means that it is a async function. But your `Flow`'s option `asyncio` is not set, which means that your flow is a sync one. So do they conflict？
2. What will happen if i delete the `async` before the `def`?

**Comment by JoanFM** [comment]
Hello @wqh17101 ,

Let me try to explain the 2 concepts: 1. having `async` in the Executor side. 2. The `asyncio` keyword for the Flow.

Let's explain point 1.

The Executor is wrapped by Jina with a GRPC server to receive requests. These servers will receive the messages with the `DocumentArrays` and will call the specific methods. Since `grpc` server runs in an event loop you can `await` coroutines if needed, therefore you can declare your `endpoint` as `async` if you want.

By declaring it `async` you turn your method into a coroutine that can be used asynchronously without blocking other requests. But for it to have any impact you will need to do some async operation in your Executor (which is NOT the case in this example).

Summary: Declare `async` your endpoint if you have any `async` call inside that would allow the Executor not to block other requests concurrently.


2. The `asyncio` keyword of the Flow has nothing to do with the Executor being `async` or not. It relates to the capacity of the `Flow` of having the `post` method return an AsyncGenerator or not. THis means that you could asynchronously send requests to the Flow and get its responses.


I hope this clarifies

**Comment by wqh17101** [comment]
Can you show some examples to compare and explain?

**Comment by JoanFM** [comment]
Code examples about what exactly?

**Comment by wqh17101** [comment]
Let me see.
For example:
I have a list of requests.
If i declare my endpoint as `async`, it can process these requests parallelly.
If i do not declare my endpoint as `async`, it will process these requests one by one.

Do you mean this?

**Comment by JoanFM** [comment]
So let me show u:

```python
from jina import Flow, Executor, requests, DocumentArray
import asyncio
import time


class MyExecutor(Executor):

    @requests(on='/foo')
    async def foo(self, docs, **kwargs):
        print(f' Received foo')
        await asyncio.sleep(
            0.1)  # I do some async work (If there is no await keyword inside the coroutine, no real win)
        print(f' Finished foo')

    @requests(on='/bar')
    def bar(self, docs, **kwargs):
        print(f' Received bar')
        time.sleep(0.1)
        print(f' Finished bar')


with Flow().add(uses=MyExecutor) as f:
    f.post(on='/foo', inputs=DocumentArray.empty(100), request_size=1)
    f.post(on='/bar', inputs=DocumentArray.empty(100), request_size=1)
```

Run this code and see the printing pattern.

**Comment by wqh17101** [comment]
Good example , and i just modify it a bit.
```
from jina import Flow, Executor, requests, DocumentArray
import asyncio
import time


class MyExecutor(Executor):

    @requests(on='/foo')
    async def foo(self, docs, **kwargs):
        print(f' Received foo')
        await asyncio.sleep(
            0.1)  # I do some async work (If there is no await keyword inside the coroutine, no real win)
        print(f' Finished foo')

    @requests(on='/bar')
    def bar(self, docs, **kwargs):
        print(f' Received bar')
        time.sleep(0.1)
        print(f' Finished bar')

    @requests(on='/aar')
    async def bar(self, docs, **kwargs):
        print(f' Received aar')
        time.sleep(0.1)
        print(f' Finished aar')

with Flow().add(uses=MyExecutor) as f:
    f.post(on='/foo', inputs=DocumentArray.empty(10), request_size=1)
    f.post(on='/bar', inputs=DocumentArray.empty(10), request_size=1)
    f.post(on='/aar', inputs=DocumentArray.empty(10), request_size=1)
```
and get res below
```
 Received foo
 Received foo
 Received foo
 Received foo
 Received foo
 Received foo
 Received foo
 Received foo
 Received foo
 Received foo
 Finished foo
 Finished foo
 Finished foo
 Finished foo
 Finished foo
 Finished foo
 Finished foo
 Finished foo
 Finished foo
 Finished foo
 Received aar
 Finished aar
 Received aar
 Finished aar
 Received aar
 Finished aar
 Received aar
 Finished aar
 Received aar
 Finished aar
 Received aar
 Finished aar
 Received aar
 Finished aar
 Received aar
 Finished aar
 Received aar
 Finished aar
 Received aar
 Finished aar
```

where is the bar's res?

**Comment by wqh17101** [comment]
It is interesting.
Is there any real scene for us to use `await`?  Like some detailed task.

**Comment by JoanFM** [comment]
Hey @wqh17101 ,

Examples of using `await` inside the Executor depends on the usage, but for instance, if ur Executor tries to connect to some external service via some async API it can be useful. Anything that can be run concurrently or is I/O bound in Executor could be run concurrently with `asyncio`.

The `asyncio` in Flow would let you have this syntax:

```
with Flow(asyncio=True, ...).add(...) as f:
   async for response in f.post(...):
       # handle response 1 by 1 in an async fashion
```
It would allow you to asynchronously send and receive requests from the Flow concurrently
