### ISSUE TITLE
Update uvicorn version

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#5999]
Release of uvicorn 0.23.2 is making our tests hang because of the way how we handle websocket Gateway.

For now, we have fixed the uvicorn version, but it would be ideal to find the reason and unpin the version to profit from new benefits from it

**Comment by JoanFM** [comment]
@MimicTester1307 please assign yourself here

**Comment by MimicTester1307** [comment]
> @MimicTester1307 please assign yourself here

@JoanFM I can't seem to assign myself, as I am not a collaborator. Please assign the issue to me.

**Comment by JoanFM** [comment]
I do not find how, but do not worry, u can start working on it

**Comment by MimicTester1307** [comment]
Alright, thanks

**Comment by MimicTester1307** [comment]
Hi @JoanFM. In trying to reproduce the error, I found a couple of things and have some questions. Maybe it's due to my setup, so I want to clarify:
1. the build is tested against Python versions 3.7 & 3.8, right? Are there plans to upgrade to a later version?
2. the current version of Jina depends on docarray <=0.21.0, but it seems that the build is configured to download the latest version of docarray. This caused some tests to fail. Please find attached a sample image below:

![image](https://github.com/jina-ai/jina/assets/57713506/16507f55-738f-442c-afa7-179eeff65e92)

I will downgrade to the recommended version of docarray, but I just wanted to point this out.

**Comment by JoanFM** [comment]
for 1. We could chnage in the future, but is not related to this issur.

for 2. Jina is compatible with every docarray version, but we had so many tests with docarray 0.21.0 that we kept most of the tests unchanged and we install that version in our ci/cd

**Comment by MimicTester1307** [comment]
Yes, the python version isn't related. I was just curious.

I see. Somehow it was the latest version of docarray that was installed in my environment. From the `extra-requirements.txt` file, the version set to be installed globally is `docarray >= 0.16.4`. Maybe along the line the tests can be updated to use the latest version of docarray. In the meantime, I'll downgrade my version and just work on this issue. Thanks

**Comment by JoanFM** [comment]
it is a really big effort to change to the docarray version, and it would not add so much value.
