### ISSUE TITLE
Should we add in our dependencies an extra tag 'tests' and exclude it from when installing '[all]'?

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#631]
**Describe the feature**
Jina's core idea is to keep dependencies as simple as possible by running pods inside docker containers when needed.
However, this poses a challenge since we should be able as much as possible to test any possible feature introduced in jina.

A possible solution to cover as much test cases as possible could be to add a new tag in setup.py and extra-requirements.txt to consider at test but without forcing any new user to install them?

**Comment by hanxiao** [comment]
In our CI test, we use
https://github.com/jina-ai/jina/blob/aa5fbe8725443417d033b02b612b4fe858bc46f9/.github/workflows/ci.yml#L53-L54

This corresponds to `pip install .[all]` but excluding those marked with specific Python version `py37` or `py38`, i.e. current env is Python 3.7 then `match-py-ver` = `all` - `py38`

**Comment by JoanFM** [comment]
I think I may have missunderstood what the pags py37 and py38 were for.

So what you mean is if I add to extra_requirements.txt:
```
faiss:       py37, py38.
```
This package will be installed for the tests, but when installing jina[all] they won't be considered?

**Comment by hanxiao** [comment]
https://github.com/jina-ai/jina/blob/master/setup.py#L57-L67

```
`all` = all deps
`match_py_ver` = (those are not tagged with either `py37` or `py38`) + 
                            (those are tagged with `py37` if the current system is Python 3.7) or (those are tagged with `py38` if the system is Python 3.8)
```

**Comment by JoanFM** [comment]
> https://github.com/jina-ai/jina/blob/93c8f1fb0bc1f36c1595be4fc56c86631b146073/setup.py#L57-L67
> 
> ```
> `all` = all deps
> `match_py_ver` = (those are not tagged with either `py37` or `py38`) + 
>                                (those are tagged with `py37` if the current system is Python 3.7) or 
>                                 (those are tagged with `py38` if the system is Python 3.8)
> ```

Ok, that is what I understood.

My point is, maybe we want some dependencies (like now faiss for instance) that we want to have them available at test time (otherwise we cannot validate that our code works), but we do not want a user to install without being fully aware of it? 

I can think that it may bring more problems and make the first jina experience a little bit unpleasant.

Does that make sense?

**Comment by hanxiao** [comment]
This is often a sign that we need to move this dependency to Hub. Specifically, we do not want to use `pip` to install packages that are:

- Packages are difficult to install, not `pip` friendly, `setup.py` is badly written
- Packages that are still experimental
- Packages that are OS/arch-specific
- Packages that are not well-maintained.

So what about the distribution of `jina`? Frankly, we don't encourage users to install heavy AI/ML dependencies via `pip install jina[some_ai_feature]`, unless the users/devs know what they are doing and have the ability to resolve dependency problem by themselves. Otherwise, our recommendation is to ship prebuilt Jina docker images to the users. For example,

- `jinaai/jina:0.3.6-tensorflow-gpu`: a Jina image with prebuilt GPU tensorflow.
- `jinaai/jina:0.3.6-faiss-0.2`: a Jina image with prebuilt faiss 0.2

It's like buying a Windows distribution with Office (or Internet Explorer 🤣 ) preinstalled. Such a building system is part of the milestone of `jina-hub` project and it's not fully implemented yet.

**Comment by JoanFM** [comment]
> This is often a sign that we need to move this dependency to Hub. Specifically, we do not want to use `pip` to install packages that are:
> 
> * Packages are difficult to install, not `pip` friendly, `setup.py` is badly written
> * Packages that are still experimental
> * Packages that are OS/arch-specific
> * Packages that are not well-maintained.
> 
> So what about the distribution of `jina`? Frankly, we don't encourage users to install heavy AI/ML dependencies via `pip install jina[some_ai_feature]`, unless the users/devs know what they are doing and have the ability to resolve dependency problem by themselves. Otherwise, our recommendation is to ship prebuilt Jina docker images to the users. For example,
> 
> * `jinaai/jina:0.3.6-tensorflow-gpu`: a Jina image with prebuilt GPU tensorflow.
> * `jinaai/jina:0.3.6-faiss-0.2`: a Jina image with prebuilt faiss 0.2
> 
> It's like buying a Windows distribution with Office (or Internet Explorer  ) preinstalled. Such a building system is part of the milestone of `jina-hub` project and it's not fully implemented yet.

Yes, I agree that this is not encouraged, so for now we accept to leave some code in jina/core untested?

**Comment by hanxiao** [comment]
unfortunately, yes.

> so for now we accept to leave some code in jina/core untested?

**Comment by JoanFM** [comment]
Understood! Closing the issue
