### ISSUE TITLE
Recommand a new framework to generate documentations

### ISSUE THREAD

**Issue by shenlu89** [jina-ai/jina#778]
Better documentation layout / look and feel of the documentation and better sorting between docs and examples and tutorials

**Describe the feature**
I find [Jina Documentations] have some issues:

* Responsive web design issues, especially on mobile.
* Cross-browser compatibility problems
* Lack JS and CSS minify and uglify

**Your proposal**

In my perspective, we can use a mature documentation framework and fill out the docs content based on it. Such as [https://docsify.js.org](https://docsify.js.org/)

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-152) by [Unito](https://www.unito.io/learn-more)

**Comment by nan-wang** [comment]
@shenlu89 Good points! It would be great if you can lead the project. Plus, there might be some pitfalls during the process. For example, we are now using [sphinx](https://www.sphinx-doc.org/en/master/) to generate the docs, which is python-friendly, and works pretty well with our current docstrings. You might need to check these points with the new proposal before moving forward.

**Comment by hanxiao** [comment]
what is the status quo of this issue?

**Comment by shenlu89** [comment]
Hi @hanxiao , I discussed it with @nan-wang . Now Jina docs were generate via sphinx automatically from python source code, but docsify have to manually edit it, because it does not support reStructuredText format right now. So we think could mimic https://docsify.js.org reconstruct Jina docs css later.

**Comment by harpreetseehra** [comment]
Documentation should be created using a proper Authoring tool like Framemaker, Oxygen, etc. It should be in XML/DITA format so that we can re-use the content, whenever required. Docs should be stored in a proper Content Management System to do proper versioning. GIT can work initially but there are just docs related CCMS like Adobe's LMS with Framemaker.

I am assuming, your current structure only creates Html. What if you want a pdf, epub, chm, or other formats? For that, we should use DITA Toolkit. Generating automatic docs from Docker or Swagger doesn't look very professional.

It should Topic-based authoring, which can be very useful in the long run.

**Comment by nan-wang** [comment]
@harpreetseehra Thanks for sharing your helpful insight. We definitely will take a look into your suggestions.

**Comment by harpreetseehra** [comment]
Thanks, I have cloned your docs and I will try to convert a few of the source files into XML format using Oxygen XML editor and then generate a Webhelp. I am sure Oxygen supports .md files, even if I don't convert them into XML, I can still play around with them and generate a Webhelp.

I will share my findings with you.

**Comment by nan-wang** [comment]
That would be really awesome! 👍

**Comment by harpreetseehra** [comment]
I noticed one thing, whenever you make any changes in the docs folder as you did 5 hours ago, it doesn't allow me to pull the latest changes again. I have to delete and clone again. Is that normal?

FYI, I am using SVN git to clone, pull, push, etc.

**Comment by nan-wang** [comment]
Nope, it sounds wired for me. The `docs` folder under `jina` repo is fully under the git control. Would you please give more details?

**Comment by harpreetseehra** [comment]
Steps to reproduce:

- Download Tortoise Git (https://tortoisegit.org/download/)
- Clone docs repo, using Tortoise git.
- Make some changes in the docs folder, like you and your team do every day from your end. For example, if you directly make changes to the folder using the web interface, do the same. If you use CLI, do that way.
- After making changes, now use Tortoise to Pull the current changes.

Expected behaviour: It should Pull the docs folder.
Current behaviour: It shows an error message "fatal: refusing to merge unrelated histories"

**Comment by hanxiao** [comment]
The reason is that `docs` repo is maintained with `git push --force`, making it "detached" to any previous commits.

What happened I guess is:
- You pull the `docs` locally, say version `A`
- Upstream docs is changed due to the merge triggers docs rebuild
- Rebuild result is `git push --force` to the `docs`, detach the head from `A`
- You pull the `docs` locally again, it should update based on `A`, however, since the upstream is detached from `A`, you get nothing.

> I noticed one thing, whenever you make any changes in the docs folder as you did 5 hours ago, it doesn't allow me to pull the latest changes again. I have to delete and clone again. Is that normal?
> 
> FYI, I am using TORTOISE git to clone, pull, push, etc.

**Comment by harpreetseehra** [comment]
Ohhh, so that's the reason why I am not able to pull after every new build. For time being, I can delete and clone again, however, in the long term it will be very irritating to delete the docs folder and clone again as it might a lot of time to do so.

I know I am asking too many questions, I have another question. The source files inside the **docs** folder, are they the real source files? They are .txt files.

I guess my question is, what is the extension of the doc source files that you work with? Are you converting .txt to .md, and then to .html? Or how does that work?

**Comment by nan-wang** [comment]
hi, there. You can find the doc building script at https://github.com/jina-ai/jina/blob/master/make-doc.sh. Besides the doctrings, we use `.rst` for writing documentation.

**Comment by harpreetseehra** [comment]
Thanks for the script. This process is new for me as I always used a proper authoring tool and a CMS for docs, however, this looks interesting.
