### ISSUE TITLE
how to set correct traverse_on when use KVSearchDriver?

### ISSUE THREAD

**Issue by xiongma** [jina-ai/jina#890]
**Describe your problem**
when jina finish vector search, the document structure like this

```java
-doc k-1
  -chunks k
      -matches k
```

when jina mapping matches' doc id by using `KVSearchDriver` from chunk index, how to set `traverse_on`? 
there are 2 options I had tried.

1. if I set `traverse_on` is chunks, and the whole logic of recursive loop is to find `chunks` doc id, not `matches`.
1. if I set `traverse_on` is matches, and the first docs in recursive loop is empty. and then it didn't mapping anything.

maybe there has something, I didn't get it.

**What is your guess?**

the solution of this problem could related to this [jina-ai/examples/pull/141](https://github.com/jina-ai/examples/pull/141)

**Environment**

**Screenshots**

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-203) by [Unito](https://www.unito.io/learn-more)

**Comment by nan-wang** [comment]
hi, there. In your case, `traverse_on` should be set to `chunks` so that the `matches` of the `chunks` are grouped into `matches` of the doc. A example can be found in the unit tests at https://github.com/jina-ai/jina/blob/master/tests/unit/drivers/test_chunk2doc_rank_drivers.py#L151. Plus, we are refactoring this part with https://github.com/jina-ai/jina/pull/889. Stay tuned.

**Comment by xiongma** [comment]
1. the unitest just show how to use `Chunk2DocRankDriver`, not how to use `KVSearchDriver`
2. in your explanation, after search nearest embedding from index, we should use `ranker` to group `matches` from `k-1` to `k` , rather than mapping `matches'` doc id by using `matches` id? but the ranker need `matches` doc id.
