### ISSUE TITLE
Avoid manual setting of attributes from parameters in all executors

### ISSUE THREAD

**Issue by bhavsarpratik** [jina-ai/jina#910]
**Describe the feature**
We have to set attributes manually from the parameters in all classes 

**Your proposal**
Add `store_attr` method to `BaseExecutor` inspired by [fastcore](https://fastpages.fast.ai/fastcore/) as explained in this [notebook](https://colab.research.google.com/drive/1tff9Is5ZNN9u3BJ-3mm10vScsWARJQEv?usp=sharing)

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-216) by [Unito](https://www.unito.io/learn-more)

**Comment by hanxiao** [comment]
i would prefer using native python>= 3.7 `data class` if we want to enable this sugary feature. Without native support, many IDE/lint tools can not recognize those attributes anymore.

Besides, in Jina Executor is nearly always used with a YAML spec, not directly be called in Python. The one who uses this sugary feature would be the executor developers.

**Comment by hanxiao** [comment]
ref: https://docs.python.org/3.7/library/dataclasses.html

**Comment by JoanFM** [comment]
Hey @bhavsarpratik ,

I can't see what benefit is extracted from seeing the notebook, would you mind elaborating a little more?

**Comment by JoanFM** [comment]
Ah ok, I see now from fastcore.

**Comment by hanxiao** [comment]
@bhavsarpratik also beware that, using `dataclass` in Jina is non-trivial mainly because `BaseExecutor` and its meta class `ExecutorType` is implemented in a non-trivial way. Especially on the `__init__`, class reading, and YAML IO-friendly. This implementation could conflict with the functionality that `dataclass` provides. I would look at the source code of `dataclass` first before adding to `BaseExecutor`.

I had this idea of refactoring `BaseExecutor` in the very early days on Jina `0.1.x`, but that was put to a low-priority and didn't follow up.

**Comment by hanxiao** [comment]
In general, `dataclass` is a nice-to-have feature as it does make our code more Pythonic and state-of-the-art. But it has to be taken very carefully and also understand the target users who enjoy this benefit is mainly the *executor developers*

**Comment by bhavsarpratik** [comment]
I agree `dataclass` has its limitations. I suggested this experimental PR for developers to write shorter pythonic code for future executors.

**Comment by hanxiao** [comment]
for reference, https://github.com/jina-ai/jina-hub/pull/400 points out a pretty smart and non-intrusive way of using `dataclass`
