### ISSUE TITLE
bug in traversing on chunks

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#952]
**Describe the bug**
In line https://github.com/jina-ai/jina/blob/master/jina/drivers/**init**.py#L329,
when passing a document with no match at one granularity. `_temp.extend(working_doc.matches)` will leads to an empty `working_docs` and accessing `working_docs[0]` results an error. 

```
       if 'chunks' in self._recur_on:
            working_docs = docs
            while working_docs[0].adjacency < self._adjacency_start:
                _temp = []
                for working_doc in working_docs:
                    _temp.extend(working_doc.matches)
                working_docs = _temp
            _traverse(working_docs, 'chunks', None, 'granularity', self._granularity_start, self._granularity_end)

```

**Describe how you solve it**

```
       if 'chunks' in self._recur_on:
            working_docs = docs
            while working_docs[0].adjacency < self._adjacency_start:
                _temp = []
                for working_doc in working_docs:
                    if working_doc.matches:
                        _temp.extend(working_doc.matches)
                if not _temp:
                    break
                working_docs = _temp
            _traverse(working_docs, 'chunks', None, 'granularity', self._granularity_start, self._granularity_end)
```

- - -

**Environment**

**Screenshots**

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-234) by [Unito](https://www.unito.io/learn-more)

**Comment by maximilianwerk** [comment]
Good catch. Should there be a warning logged as well? It would be nice for understanding, when one configured the ranges wrongly. On the other hand in the real world that might spam quite a lot of log messages.

I am not sure, how gracefully we should accept wrong ranges. Can you give an example, where this can happen with correct ranges, but just wrong documents?

**Comment by maximilianwerk** [comment]
Sorry for not spotting this before: it should rather be a `return` then a `break`, since the defined ranges clearly do not match the document structure and thus there should be no more traversal. While accepting non-matching structures, it is not good to do some non-well-defined behavior with the ranges. `granularity_range=(1,1)` and `recur_on=['matches']` should always mean, that matches on the first layer of chunks are touched. If we break, then sometimes matches of the zeroes layer of chunks are touched.
